---
## KUBERNETES
## ----------

api_public_ip: "{{ lb_ip_apik8s }}"
api_private_ip: 10.254.0.1
api_domain: apik8s-{{ env_site }}.e-unicred.com.br

etcd_version: 3.3.11

kubernetes_version: 1.15.3
kubernetes_dir: /var/lib/kubernetes
kubernetes_kubelet_dir: /var/lib/kubelet
kubernetes_kube_proxy_dir: /var/lib/kube-proxy
kubernetes_cluster_name: "{{ cluster_domain | default('cluster.local') }}"
kubernetes_cluster_cidr: 172.18.0.0/16
kubernetes_cluster_dns: 10.254.0.10

network_plugin: cni
max_pods_per_node: 110
permissive_serviceaccount: false

istio_version: 1.1.5

token_prometheus: f9bee5bcbcdc7ea23338eb8f9759f823
