---
- name: addons | coredns
  include: coredns.yml
  when:
    - "'master' in group_names"
    - deploy_addons
  tags:
    - coredns


- name: addons | metrics-server
  include: metrics-server.yml
  when:
    - "'master' in group_names"
    - deploy_addons
  tags:
    - metrics-server


- name: addons | helm-tiller
  include: helm-tiller.yml
  when:
    - "'master' in group_names"
    - deploy_addons
  tags:
    - helm-tiller


- name: addons | kube-state-metrics
  include: kube-state-metrics.yml
  when:
    - "'master' in group_names"
    - deploy_addons
  tags:
    - kube-state-metrics


- name: addons | prometheus
  include: prometheus.yml
  when:
    - "'master' in group_names"
    - deploy_addons
  tags:
    - prometheus

- name: addons | istio
  include: istio.yml
  when:
    - "'master' in group_names"
    - deploy_addons
  tags:
    - istio

