---
- name: Install tools
  yum: 
    state: installed
    name: 
      - policycoreutils-python
      - libselinux-python

- name: Set selinux config
  selinux: policy=targeted state={{ selinux_mode }}
